version: "3.9"

services:
  backend:
    build:
      context: ./mockly-backend
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    tmpfs:
      - /tmp
    restart: unless-stopped

  frontend:
    build:
      context: ./mockly-frontend
      dockerfile: Dockerfile
    environment:
      - VITE_USE_MOCK=false
      - VITE_BACKEND_URL=http://backend:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
